seed_everything : 1

model:
  loss_params:
    name : KENNBCEMultiloss
    alpha : .5
  ET_Network_params:
    name : BaseEntityTypingNetwork
    network_params:
      encoder_params:
        name : DistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        freeze_encoder : True
      type_encoder_params:
        name : OneHotTypeEncoder
        trainable: False
      input_projector_params:
        # name : Classifier
        name : KENNClassifierMultiloss
        clause_file_path : entity_typing_experiments/kenn_experiments/clause_files/custom_top_down_clause.txt # if u want to generate AND use a clause file, 
                                                                                                              # this has to be equal to
                                                                                                              # data.dataset_reader_params.clause_output_path 
        save_training_data : False
        layers_parameters: 
          '0':
            in_features : encoder_dim
            out_features: 512
            use_dropout: True
            activation: relu
          '1':
            in_features: 512
            out_features : type_number
            use_dropout: False
            activation: sigmoid

trainer:
  # resume_from_checkpoint: trained_models/epoch=14-step=1979.ckpt
  gpus: 1
  limit_train_batches: .2
  max_epochs : 30
  callbacks:
    # - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    #   init_args:
    #     dirpath: trained_models/
    #     monitor: val_loss
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    train: datasets/ren_et_al/bbn/train.json
    dev: datasets/ren_et_al/bbn/dev.json
    test: datasets/ren_et_al/bbn/test-12k.json
  dataset_reader_params:
    # name : BaseDataset
    name : DatasetWithKENN
    types_file_path : datasets/ren_et_al/bbn/all_types.txt
    # clause_output_path : entity_typing_experiments/kenn_experiments/clause_files/top_down_clause.txt
    learnable_clause_weight : True
    clause_weight : 0.5
    kb_mode : top_down
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 1
    max_right_words: 2
    max_left_words: 2
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    train:
      batch_size: 64
      shuffle: True
    dev:
      batch_size: 8
    test:
      batch_size: 8

logger:
  project : entity_typing_framework_prove
  entity : noonebug
  name : Kenn20p