seed_everything : 1

model:
  loss_params:
    name : KENNBCEMultiloss
    alpha : .3
  ET_Network_params:
    name : BaseEntityTypingNetwork
    network_params:
      encoder_params:
        name : DistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        # adapter_arch : Pfeiffer
        # reduction_factor : 16
      type_encoder_params:
        name : OneHotTypeEncoder
        trainable: False
      input_projector_params:
        # name : KENNClassifier
        name : KENNClassifierMultiloss
        clause_file_path: kb_prova/prova
        save_training_data: False
        layers_parameters: 
          '0':
            in_features : encoder_dim
            out_features: 512
            use_dropout: True
            activation: relu
          '1':
            in_features: 512
            out_features : type_number
            use_dropout: False
            activation: sigmoid
  inference_params:
    name: BaseInference
    threshold: 0.5

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 20
  max_epochs : 5
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: trained_models/prova/
        monitor: val_loss
        filename: prova
        save_weights_only: True
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    train: datasets/bbn/train.json
    dev: datasets/bbn/dev.json
    test: datasets/bbn/test-12k.json
  # train_test_mapping:
  #   livingthing: living_thing
  dataset_reader_params:
    name : KENNDataset
    types_file_path: datasets/bbn/all_types.txt
    clause_output_path: kb_prova/prova
    learnable_clause_weight: True
    clause_weight: 1.0
    kb_mode: top_down
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 2
    max_right_words: 2
    max_left_words: 2
    max_tokens: 5
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    train:
      batch_size: 8
      shuffle: True
    dev:
      batch_size: 8
    test:
      batch_size: 8
  rw_options:
    modality: Load # in [Create, CreateAndSave, Load]
    dirpath: datasets/bbn/tokenized 
    light: False
  

logger:
  project : tmp
  entity : cbe
  name : debug
  config_file: entity_typing_experiments/prova/prova.yaml