dataset_reader_params:
  name : BaseDataset
dataset_params:
  name: ET_Dataset
dataloader_params:
    name: torch.DataLoader
    pretraining_train:
      batch_size: 64
      shuffle: True
    pretraining_dev:
      batch_size: 64
    pretraining_test:
      batch_size: 64
    incremental_train:
      batch_size: 64
      shuffle: True
    incremental_dev:
      batch_size: 64
    incremental_test:
      batch_size: 64