seed_everything : 1

model:
  # new_type_number: 1
  checkpoint_to_load: trained_models/pretraining/pretraining_location.ckpt
  loss_params:
    name : BCELossForET
  ET_Network_params:
    name : EntityTypingNetworkForIncrementalTraining
    network_params:
      encoder_params:
        name : DistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        freeze_encoder : True
      type_encoder_params:
        name : OneHotTypeEncoder
        trainable: False
      input_projector_params:
        name : Classifier
        layers_parameters: 
          '0':
            in_features : encoder_dim
            out_features: 512
            use_dropout: True
            activation: relu
          '1':
            in_features: 512
            out_features : type_number
            use_dropout: False
            activation: sigmoid

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 10
  max_epochs : 10
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: trained_models/incremental/
        monitor: losses/val_loss
        filename: incremental_locationcity
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: losses/val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    pretraining_train: datasets/datasets_for_incremental_training/figer/pretraining_location.json
    # pretraining_train: datasets/datasets_for_incremental_training/figer/pretraining_location_dev.json
    pretraining_dev: datasets/datasets_for_incremental_training/figer/pretraining_location_dev.json
    pretraining_test: datasets/datasets_for_incremental_training/figer/pretraining_location_test.json
    incremental_train: datasets/datasets_for_incremental_training/figer/incremental_locationcity.json
    # incremental_train: datasets/datasets_for_incremental_training/figer/incremental_locationcity_dev.json
    incremental_dev: datasets/datasets_for_incremental_training/figer/incremental_locationcity_dev.json
    incremental_test: datasets/datasets_for_incremental_training/figer/incremental_locationcity_test.json
  dataset_reader_params:
    name : BaseDataset
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 1
    max_right_words: 1
    max_left_words: 1
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    pretraining_train:
      batch_size: 512
      shuffle: True
    pretraining_dev:
      batch_size: 512
    pretraining_test:
      batch_size: 512
    incremental_train:
      batch_size: 512
    incremental_dev:
      batch_size: 512
    incremental_test:
      batch_size: 512
    

logger:
  project : entity_typing_framework_prove
  entity : noonebug
  name : incremental_figer_location_city